### ISSUE TITLE
Not working with media hosted on Discord CDN after recent change

### ISSUE THREAD

**Issue by Crunklio** [Syncxv/vc-gif-collections#1]
Now that Discord is planning to restrict linking to its CDN outside of the client, the link of every file hosted on the CDN is appended with additional arguments, e.g.

> https://cdn.discordapp.com/attachments/562710813123543040/1158041034140418078/DxHxbVEUwAA2ILb.jpg_large.jpg?ex=651acd41&is=65197bc1&hm=d23547d25a79ae080761936f12ba18b2664d1e3109aefbd098caa3630be88693&

which prevents the plugin's context menu options from showing up.

**Comment by Syncxv** [comment]
sorry for the late reply. should be fixed here https://github.com/Syncxv/vc-gif-collections/commit/d6e1a26d890bad24bc61c84a25901f6c57e18d13

this plugin is a terrible mess so i plan to rewrite the entire plugin after my exams. but no promises hehe
