### ISSUE TITLE
broken

### ISSUE THREAD

**Issue by BigBadBodyPillow** [Syncxv/vc-gif-collections#3]
if you right click on a gif in a channel it shows the options to add to a collection or create a new one however the collections do not show up in the gif menu

**Comment by Syncxv** [comment]
did you switch clients (like stable to canary) or switch pc? if you did then export the collections from the original client and import it to whatever client you're using right now.

my collections are still showing up so its most likely not broken.
if you're certain its broken provide ways to reproduce this
